name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"   # update setiap hari 00:00 UTC

jobs:
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: WakaTime Readme
        uses: athul/waka-readme
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: "true"
          TIME_RANGE: "last_7_days"
          SHOW_TOTAL: "true"
